language: python

python:
  - "2.7"

dist: trusty
sudo: required
before_install:
  - sudo apt-get install -y unixodbc unixodbc-dev
  - sudo apt-get install -y libboost-all-dev
script:
  - mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=./dist .. 
  - make -j4
  - ctest --verbose
  - make install
  - cd dist
  - python setup.py sdist
  - cd dist
  - virtualenv venv
  - source venv/bin/activate
  - pip install *.tar.gz