language: cpp
dist: trusty
sudo: required
before_install:
  - sudo apt-get install unixodbc unixodbc-dev --force
  - sudo apt-get install libboost-all-dev --force
script:
  - mkdir build && cd build && cmake .. && make -j4