language: cpp
dist: trusty
sudo: required
before_install:
  - sudo apt-get install unixodbc unixodbc-dev
  - sudo apt-get install libboost-all-dev
script:
  - mkdir build && cd build && cmake .. && make -j4