version: '{branch} - #{build}'

image: Visual Studio 2015

platform:
  - x64

environment:
  PYTHON: C:\Python36-x64
  BOOST_ROOT: C:\Libraries\boost_1_63_0
  TURBODBC_TEST_CONFIGURATION_FILES: query_fixtures_postgresql.json,query_fixtures_mysql.json
  MYSQL_PWD: Password12!
  PGUSER: postgres
  PGPASSWORD: Password12!

install:
- cmd: >-
    git submodule update --init --recursive

    SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

    pip install numpy pytest mock

    echo %PYTHON%

build_script:
- cmd: >-
    cd ..

    mkdir turbodbc_build

    cd turbodbc_build

    cmake ..\turbodbc -DPYBIND11_PYTHON_VERSION=3.6 -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release -A x64

    cmake --build . --config Release

test_script:
- cmd: >-
    type c:\Windows\ODBCINST.INI

    SET PATH=C:\Program Files\PostgreSQL\9.6\bin;C:\Program Files\MySQL\MySQL Server 5.7\bin;%PATH%

    psql -c "CREATE DATABASE test_db;"

    mysql -u root -e "CREATE DATABASE test_db;"

    ctest --verbose -C Release